apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::190235241386:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::190235241386:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-HaA5oaHRjQH2
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-11T19:52:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1321"
  uid: 6e95fded-7897-40f3-a8c2-fd1d1111da7f
